config/routes.rb
Rails.application.routes.draw do
  resources :medium_types
  resources :labels_posts
  resources :posts
  resources :labels
  resources :authors
  resources :upload_musings_dbs, only: [:index, :create]
  root to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/label.rb
class Label < ApplicationRecord
    has_many :labels_posts, dependent: :destroy
    has_many :posts, through: :labels_posts

    scope :ordered, -> {order(name: :asc)}


    def self.create_if_non_exist(label_name_array)
      label_name_array.each do |label_name|
        self.create(name: label_name) if !self.find_by(name: label_name).present?
      end
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[ show edit update destroy ]

  # GET /labels or /labels.json
  def index
    @labels = Label.all.ordered.includes(posts: [:medium_type, :author, :labels])
  end

  # GET /labels/1 or /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels or /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to label_url(@label), notice: "Label was successfully created." }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1 or /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to label_url(@label), notice: "Label was successfully updated." }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1 or /labels/1.json
  def destroy
    @label.destroy

    respond_to do |format|
      format.html { redirect_to labels_url, notice: "Label was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def label_params
      params.require(:label).permit(:name)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
        <% label.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Labels
  <%= link_to '+ New Medium', new_label_path, class: "btn btn-sm btn-success"%>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td>
          <%= label.name %>
          <% if label.posts.any? %>
             <button class="badge badge-pill badge-info" data-toggle="collapse" data-target="#<%="label_posts_#{label.id}"%>"><%= label.posts.size %></button>
          <% end %>
        </td>
        <td><%= link_to 'Show', label, class: "btn btn-sm btn-info" %></td>
        <td><%= link_to 'Edit', edit_label_path(label), class: "btn btn-sm btn-info" %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>

      <tr>
        <% if label.posts.any? %>
          <td colspan="4" id="label_posts_<%=label.id%>" class="collapse">
              <% label.posts.ordered.each do |post| %>
                <%= render partial: "posts/post", locals: {post: post}%>
                <br>
              <% end %>
          </td>
        <% end %>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

<br>
<hr>

<% @label.posts.ordered.each do |post| %>
  <%= render partial: "posts/post", locals: {post: post}%>
  <br>
<% end %>

<br><br>