config/routes.rb
Rails.application.routes.draw do
  resources :medium_types
  resources :labels_posts
  resources :posts
  resources :labels
  resources :authors
  resources :upload_musings_dbs, only: [:index, :create]
  root to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :posts
  scope :ordered, -> {order(name: :asc)}
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all.ordered.includes(posts: [:medium_type, :author, :labels])
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Authors
  <%= link_to '+ New Author', new_author_path, class: "btn btn-sm btn-success"%>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td>
          <%= author.name %>
          <% if author.posts.any? %>
             <button class="badge badge-pill badge-info" data-toggle="collapse" data-target="#<%="author_posts_#{author.id}"%>"><%= author.posts.size %></button>
          <% end %>
        </td>
        <td><%= link_to 'Show', author, class: "btn btn-sm btn-info" %></td>
        <td><%= link_to 'Edit', edit_author_path(author), class: "btn btn-sm btn-info" %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %></td>
      </tr>

      <tr>
        <% if author.posts.any? %>
          <td colspan="4" id="author_posts_<%=author.id%>" class="collapse">
              <% author.posts.ordered.each do |post| %>
                <%= render partial: "posts/post", locals: {post: post}%>
                <br>
              <% end %>
          </td>
        <% end %>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

<br>
<hr>

<% @author.posts.ordered.each do |post| %>
  <%= render partial: "posts/post", locals: {post: post}%>
  <br>
<% end %>

<br><br>