config/routes.rb
Rails.application.routes.draw do
  resources :medium_types
  resources :labels_posts
  resources :posts
  resources :labels
  resources :authors
  resources :upload_musings_dbs, only: [:index, :create]
  root to: 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  attr_accessor :labels_raw

  belongs_to :author
  belongs_to :medium_type

  has_many :labels_posts, dependent: :destroy
  has_many :labels, through: :labels_posts

  has_rich_text :summary

  validates_presence_of :title
  validates_presence_of :summary

  scope :ordered, -> {order(created_at: :desc)}


  def persist_raw_labels
    self.labels_posts.destroy
    self.reload
    sanitized_label_array = self.labels_raw.split(";").map {|label| label.strip.titleize}.uniq
    Label.create_if_non_exist(sanitized_label_array)
    LabelsPost.create_if_non_exist(post: self, label_name_array: sanitized_label_array)
  end

  def convert_persisted_labels_to_raw
    labels.map(&:name).join("; ")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.ordered.includes(:medium_type, :author, :labels)
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post.labels_raw = @post.convert_persisted_labels_to_raw
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        @post.persist_raw_labels
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @post.persist_raw_labels
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    @post.summary.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author_id, :medium_type_id, :reference, :summary, :labels_raw)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <%= form.label :author_id do %>
      Author <%= link_to "+ Author", new_author_path, class: "btn btn-xs btn-success" %>
      <% end %>
      <%= form.collection_select :author_id, Author.all.ordered, :id, :name, {include_blank: "Please Select"}, class: "form-control" %>
    </div>

    <div class="col-sm-6">
      <%= form.label :medium_type_id do %>
      Medium <%= link_to "+ Medium", new_medium_type_path, class: "btn btn-xs btn-success" %>
      <% end %>
      <%= form.collection_select :medium_type_id, MediumType.all.ordered, :id, :name, {include_blank: "Please Select"}, class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :labels_raw do %>
      Labels
      <button type="button" class="btn btn-xs btn-info" data-toggle="tooltip" data-placement="right" title="Add a semi-colon between labels. Typing in a label that does not yet exist will create the label.">
        ?
      </button>
    <% end %>
    <%= form.text_field :labels_raw, class: "form-control", id: "post_labels_raw" %>
  </div>

  <br>

  <div class="card bg-light text-dark">
    <div class="card-body">
      <p class="text-info">Click to Easily Add Labels to this Post.<p>
        <% Label.all.ordered.each do |label| %>
          <button type="button" class="btn btn-sm btn-info post-label-easy-add-btn"><%=label.name%></button>
        <% end %>
    </div>
  </div>


  <div class="field">
    <%= form.label :reference %>
    <%= form.text_field :reference, class: "form-control"%>
  </div>

  <br>
  <hr>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="field">
  <%= form.label :summary %>
  <%= form.rich_text_area :summary %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br><br><br><br>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-header">
      <div class="row">
        <div class="col-sm-12">
          <h3><%= post.title %></h3>
        </div>
      </div>
  </div>
  <div class="card-body">
    <%= post.summary %>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-sm-4">
        <strong>Author:</strong>
        <%= post.author.try(:name) %>
      </div>
      <div class="col-sm-4">
        <strong>Medium:</strong>
        <%= post.medium_type.try(:name) %>
      </div>
      <div class="col-sm-4">
        <% if post.reference.present? %>
          <%= link_to "Reference", post.reference %>
        <% end %>
      </div>
      <div class="col-sm-12">
        <strong>Labels:</strong>
        <% post.labels.each do |label| %>
           <span class="badge badge-primary"><%=label.name%></span>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Posts
  <%= link_to '+ New Post', new_post_path, class: "btn btn-sm btn-success"%>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Medium</th>
      <th>Reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.author.try(:name) %></td>
        <td><%= post.medium_type.try(:name) %></td>
        <td><%= post.reference %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "post", locals: {post: @post} %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>